- name: "[Prerequisites] Disable firewalld and NetworkManager."
  service: name={{item}} state=stopped enabled=no  
  with_items:
    - "firewalld"
    - "NetworkManager"  

- name: "[Prerequisites] Disable SELinux"
  selinux:
    policy: targeted
    state: permissive

- name: "Install repositorie packages for OpenStack"
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - "epel-release"
    - "centos-release-openstack-train"
    - "vim"
    - "chrony"
  register: result

- name: "Guarantee OpenStack repo enabled"
  yum:
    enablerepo: centos-openstack-train
  when: result is success
  register: result

#- name: "Updating packages"
#  yum:
#    name: '*'
#    state: latest 
#  when: result is success
 
- name: "Installing openstack client"
  yum:
    name: "python3-openstackclient"
    state: present

               
