---
# tasks file for memcached

- name: "Installing Memcached"
  dnf:
    name: "{{item}}"
    state: present
  loop:
  - memcached
  - python3-memcached
  register: dnf_res
  retries: 3
  delay: 10
  until: dnf_res.rc == 0

- name: "Copying template for /etc/sysconfig/memcached"
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached

- name: "Enabling Memcached Service"
  systemd:
    name: memcached
    state: started
    enabled: yes
