---
# tasks file for memcached

- name: "Installing Memcached"
  yum:
    name: "{{item}}"
    state: present
  loop:
  - memcached
  - python-memcached

- name: "Copying template for /etc/sysconfig/memcached"
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached

- name: "Enabling Memcached Service"
  systemd:
    name: memcached
    enabled: yes
